definitions:
  api.APIError:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  models.Chat:
    description: Represents a single WhatsApp chat (one-on-one or group).
    properties:
      description:
        description: Description for group chats
        example: Group for project updates
        type: string
      isGroup:
        description: Indicates if the chat is a group
        type: boolean
      jid:
        description: JID of the chat
        example: 1234567890@s.whatsapp.net
        type: string
      name:
        description: Display name of the chat
        example: John Doe
        type: string
      participants:
        description: List of participants for group chats
        items:
          $ref: '#/definitions/models.Participant'
        type: array
      pfp:
        example: ""
        type: string
    type: object
  models.Message:
    description: Represents a single WhatsApp message.
    properties:
      chatJID:
        description: JID of the chat the message belongs to
        example: 1234567890@s.whatsapp.net
        type: string
      id:
        description: Unique ID of the message
        example: ABCD123
        type: string
      isFromMe:
        description: Indicates if the message was sent by the client
        type: boolean
      senderJID:
        description: JID of the sender
        example: 0987654321@s.whatsapp.net
        type: string
      text:
        description: Text content of the message
        example: Hello World!
        type: string
      timestamp:
        description: Unix timestamp of the message
        type: integer
    type: object
  models.Participant:
    description: Represents a single participant in a group chat.
    properties:
      isAdmin:
        description: Indicates if the participant is an admin
        type: boolean
      jid:
        description: JID of the participant
        example: 1234567890@s.whatsapp.net
        type: string
    type: object
  models.SendMessageRequest:
    description: Request body for sending a message.
    properties:
      jid:
        description: JID of the recipient
        example: 1234567890@s.whatsapp.net
        type: string
      text:
        description: Text content of the message
        example: Hello from TextPilot!
        type: string
    type: object
info:
  contact: {}
paths:
  /clients/{clientID}/chats:
    get:
      description: Retrieves a list of all contacts and groups (chats) associated
        with a specific client.
      parameters:
      - description: Client ID
        in: path
        name: clientID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of chats retrieved successfully
          schema:
            items:
              $ref: '#/definitions/models.Chat'
            type: array
        "404":
          description: Client not found
          schema:
            $ref: '#/definitions/api.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.APIError'
      summary: Get all chats for a client
      tags:
      - clients
  /clients/{clientID}/chats/{chatID}:
    get:
      description: Retrieves detailed information for a specific chat, including participants
        for groups.
      parameters:
      - description: Client ID
        in: path
        name: clientID
        required: true
        type: string
      - description: Chat JID (e.g., 1234567890@s.whatsapp.net or 123456-7890@g.us)
        in: path
        name: chatID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Chat details retrieved successfully
          schema:
            $ref: '#/definitions/models.Chat'
        "400":
          description: Invalid chat ID format
          schema:
            $ref: '#/definitions/api.APIError'
        "404":
          description: Client or chat not found
          schema:
            $ref: '#/definitions/api.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.APIError'
      summary: Get chat details
      tags:
      - clients
  /clients/{clientID}/disconnect:
    post:
      consumes:
      - application/json
      description: Disconnects the specified client, closes the WhatsApp session,
        and cleans up resources.
      parameters:
      - description: Client ID
        in: path
        name: clientID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success message
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Client not found
          schema:
            $ref: '#/definitions/api.APIError'
      summary: Disconnect a WhatsApp client
      tags:
      - clients
  /clients/{clientID}/events:
    get:
      description: Establishes a Server-Sent Events (SSE) connection to stream real-time
        WhatsApp events (e.g., QR codes, messages, connection status).
      parameters:
      - description: Client ID
        in: path
        name: clientID
        required: true
        type: string
      produces:
      - text/event-stream
      responses:
        "200":
          description: Event stream established
          schema:
            type: string
        "404":
          description: Client not found
          schema:
            $ref: '#/definitions/api.APIError'
        "500":
          description: Streaming unsupported or Internal Server Error
          schema:
            $ref: '#/definitions/api.APIError'
      summary: Stream real-time events for a client
      tags:
      - clients
  /clients/{clientID}/messages/send:
    post:
      consumes:
      - application/json
      description: Sends a text message to a specified JID (Jabber ID) for a given
        client.
      parameters:
      - description: Client ID
        in: path
        name: clientID
        required: true
        type: string
      - description: Message details
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/models.SendMessageRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Message sent successfully
          schema:
            $ref: '#/definitions/models.Message'
        "400":
          description: Invalid request body or JID format
          schema:
            $ref: '#/definitions/api.APIError'
        "404":
          description: Client not found
          schema:
            $ref: '#/definitions/api.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.APIError'
      summary: Send a text message
      tags:
      - clients
  /clients/connect:
    post:
      consumes:
      - application/json
      description: Initializes a new WhatsApp client and returns a server-generated
        clientID.
      produces:
      - application/json
      responses:
        "200":
          description: Client ID
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.APIError'
      summary: Connect a new WhatsApp client
      tags:
      - clients
swagger: "2.0"
